# Generated by Django 4.2.7 on 2023-11-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElevatorSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("no_of_floors", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "door_status",
                    models.CharField(
                        choices=[("open", "Open"), ("close", "Close")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("current_floor", models.PositiveIntegerField(default=1)),
                ("next_floor", models.PositiveIntegerField(default=1)),
                ("previous_floor", models.PositiveIntegerField(default=1)),
                (
                    "elevator_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elevator_system",
                        to="core.elevatorsystem",
                    ),
                ),
            ],
        ),
    ]
