# Generated by Django 4.2.7 on 2023-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_elevatorrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elevatorrequest",
            name="is_busy",
        ),
        migrations.AddField(
            model_name="elevatorrequest",
            name="request_status",
            field=models.CharField(
                choices=[("done", "Done"), ("in_process", "In_Process")],
                default="In_Process",
                max_length=20,
            ),
        ),
    ]
