# Generated by Django 4.2.7 on 2023-11-17 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_elevatorrequest_is_busy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevatorrequest",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
