# Generated by Django 4.2.7 on 2023-11-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_elevatorrequest_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevatorrequest",
            name="request_status",
            field=models.CharField(
                choices=[
                    ("done", "Done"),
                    ("in_service", "In_Service"),
                    ("in_process", "In_Process"),
                ],
                default="In_Process",
                max_length=20,
            ),
        ),
    ]
