# Generated by Django 4.2.7 on 2023-11-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_elevatorrequest_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevatorrequest",
            name="elevator_system",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elevator",
                to="core.elevatorsystem",
            ),
            preserve_default=False,
        ),
    ]
